
[helpers]

[default]
depends = []

[zsh.files]
"zshrc" = "~/.zshrc"

[starship.files]
"starship.toml" = "~/.config/starship.toml"

[kitty.files]
"kitty" = "~/.config/kitty"

[fish.files]
"fish" = "~/.config/fish"

[default.variables]
