
[helpers]

[default]
depends = []

[zsh]
depends = ["starship"]

[zsh.files]
"zsh/zshrc" = "~/.zshrc"

[starship.files]
"starship/starship.toml" = "~/.config/starship.toml"

[starship.variables]
starship.executable = "starship"
starship.use_experimental_config = false

[kitty]
depends = ["palette"]

[kitty.files]
"kitty" = "~/.config/kitty"

[kitty.variables]
kitty.font.family = "JetBrains Mono"
kitty.font.bold = "auto"
kitty.font.italic = "auto"
kitty.font.bold_italic = "auto"
kitty.shell = "bash"

[fish.files]
"fish" = "~/.config/fish"

[bash.files]
"bash" = "~/"

[palette]

[default.variables]
