
[helpers]

[default]
depends = []

[zsh]
depends = ["starship"]

[zsh.files]
"zsh/zshrc" = "~/.zshrc"

[starship.files]
"starship/starship.toml" = "~/.config/starship.toml"

[starship.variables]
starship.executable = "starship"
starship.use_experimental_config = false

[kitty.files]
"kitty" = "~/.config/kitty"

[fish.files]
"fish" = "~/.config/fish"

[default.variables]
